name: Deploy org-service

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ACR_SERVER: urbancarregistry.azurecr.io
  RESOURCE_GROUP: urbancar-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login a Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login a ACR
        uses: docker/login-action@v3
        with:
          registry: urbancarregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build y push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: urbancarregistry.azurecr.io/org-service:latest

      - name: Deploy a Container Apps
        run: |
          az containerapp update \
            --name org-service \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_SERVER/org-service:latest \
            --output none
          echo "org-service desplegado ✓"
